<?php

return[

    'constants'=>[
        'VERSION'=>env('JAZZCASH_VERSION'),
        'LANGUAGE'=>env('JAZZCASH_LANGUAGE'),
        'MERCHANT_ID'=>env('JAZZCASH_MERCHANT_ID'),
        'PASSWORD'=>env('JAZZCASH_PASSWORD'),
        'CURRENCY_CODE'=>env('JAZZCASH_CURRENCY_CODE'),
        'RETURN_URL'=>env('JAZZCASH_RETURN_URL'),
        'INTEGERITY_SALT'=>env('JAZZCASH_INTEGERITY_SALT'),
        'TRANSACTION_POST_URL'=>env('JAZZCASH_TRANSACTION_POST_URL'),
    ],
];